import "./globals.css";
import "../styles/styles.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "haksubotti",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-gray-100`}>
        <div className="mx-auto max-w-7xl p-4">
          <header className="p-4 bg-white shadow-md">
            <nav className="flex justify-between items-center">
              <a
                href="/"
                className="text-lg font-semibold text-gray-800 hover:text-gray-600"
              >
                Home
              </a>
              <div>{/* Other navigation links */}</div>
            </nav>
            <h1 className="text-center text-2xl font-bold text-gray-800 my-4">
              haksubotti
            </h1>
          </header>
          <main className="p-4 bg-white mt-4 shadow-md">{children}</main>
          <footer className="p-4 bg-white mt-4 shadow-md text-center">
            <p className="text-gray-700">&copy; 2023 haksubotti</p>
          </footer>
        </div>
      </body>
    </html>
  );
}
